create table users (
    id                 bigint generated by default as identity primary key not null,
    username           varchar(150) not null unique,
    email              varchar(150) not null unique,
    encrypted_password varchar(255) not null,
    created_at         timestamp without time zone not null,
    is_email_verified  boolean not null default false
);

create table email_token (
     id bigint generated by default as identity primary key not null,
     user_id bigint not null,
     token uuid not null,
     created_at timestamp without time zone not null,
     expires_at timestamp without time zone not null,
     constraint fk_user foreign key (user_id) references users(id) on delete cascade
);

create table calendar (
        id bigint generated by default as identity primary key not null,
        user_id bigint not null,
        title varchar(250) not null,
        set_at timestamp without time zone not null,
        reminder_at timestamp without time zone not null,
        constraint fk_user foreign key (user_id) references users(id)
);

create table target (
        id bigint generated by default as identity primary key not null,
        user_id bigint not null,
        title varchar(250) not null,
        created_at timestamp without time zone not null,
        deadline timestamp without time zone not null,
        tasks_count int not null default 0,
        progress int check ( progress >= 0 and progress <= 100 ) not null,
        constraint fk_user foreign key (user_id) references users(id) on delete cascade
);

create table task (
        id bigint generated by default as identity primary key not null,
        target_id bigint not null,
        title varchar(250) not null,
        is_completed boolean not null,
        constraint fk_target foreign key (target_id) references target(id) on delete cascade
);

create table notes (
        id bigint generated by default as identity primary key not null,
        note_id uuid not null unique,
        user_id bigint not null,
        title varchar(100) not null,
        tag varchar(100),
        created_at timestamp without time zone not null,
        last_activity timestamp without time zone not null,
        foreign key (user_id) references users(id) on delete cascade
);

create table snapshots (
        id bigint generated by default as identity primary key not null,
        note_id bigint not null unique,
        snapshot_id varchar(255) not null unique,
        size bigint not null,
        created_at timestamp without time zone not null,
        foreign key (note_id) references notes(id) on delete cascade
);

create table assets (
        id bigint generated by default as identity primary key not null,
        note_id bigint not null,
        asset_id varchar(255) not null unique,
        type varchar(100) not null,
        size bigint not null,
        created_at timestamp without time zone not null,
        foreign key (note_id) references notes(id) on delete cascade
);